return {
  --   -- override nvim-cmp and add cmp-emoji
  --   {
  --     "hrsh7th/nvim-cmp",
  --     dependencies = { "hrsh7th/cmp-emoji" },
  --     ---@param opts cmp.ConfigSchema
  --     opts = function(_, opts)
  --       table.insert(opts.sources, { name = "emoji" })
  --     end,
  --   },
  --
  --   -- change some telescope options and a keymap to browse plugin files
  --   {
  --     "nvim-telescope/telescope.nvim",
  --     keys = {
  --       -- add a keymap to browse plugin files
  --       -- stylua: ignore
  --       {
  --         "<leader>fp",
  --         function() require("telescope.builtin").find_files({ cwd = require("lazy.core.config").options.root }) end,
  --         desc = "Find Plugin File",
  --       },
  --     },
  --     -- change some options
  --     opts = {
  --       defaults = {
  --         layout_strategy = "horizontal",
  --         layout_config = { prompt_position = "top" },
  --         sorting_strategy = "ascending",
  --         winblend = 0,
  --       },
  --     },
  --   },
}
